name: ci

on:
  push:
    branches:
    - main
    - release/*
  pull_request:
    branches:
    - main
    - release/*
env:
  CARGO_INCREMENTAL: 0
  CI: 1
  RUST_BACKTRACE: short
  RUSTFLAGS: "-D warnings"

jobs:
  cargo-test:
    name: cargo test (${{ matrix.os }} / ${{ matrix.rust-version }} / ${{ matrix.runtime }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        rust-version: [stable, beta, nightly]
        runtime: [runtime-tokio, runtime-agnostic]
        include:
        - rust-version: nightly
          continue-on-error: true
    steps:
    - uses: actions/checkout@v4
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.rust-version }}
    - name: Run cargo test
      continue-on-error: ${{ matrix.continue-on-error || false }}
      run: |
        cargo +${{ matrix.rust-version }} test --workspace --no-default-features --features ${{ matrix.runtime }}

  cargo-audit:
    name: cargo audit
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - id: install-rust
      name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
    - name: install-audit
      run: cargo install cargo-audit --locked
    - name: run cargo audit
      run: cargo audit

  cargo-clippy:
    name: cargo clippy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - id: install-rust
      name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@1.82.0
      with:
        components: clippy
    - name: Run cargo clippy
      run: cargo clippy

  cargo-fmt:
    name: cargo fmt
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - id: install-rust
      name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt
    - name: Run cargo fmt
      run: cargo +${{ steps.install-rust.outputs.name }} fmt --all -- --check
